### PR TITLE
Fix for sensors that return a table of cell values.

### PR DESCRIPTION
**Pull request by daveEccleston**
Added new function getCellVoltage( voltageSensorIn )
    For voltage sensors that return a table of cell voltages, add up the cell voltages to get a total cell voltage.
    Otherwise, just return the value

Updated all references that were calling getValue directly on the sensor to use the new getCellVoltage method.

FrSky FLVSS LiPo Voltage Sensor With Smart Port is the particular sensor that returns a table of cells.

### CODE REVIEW

**Comment by RCdiy** [comment]
Thank you :)
I will look at it.

**Comment by daveEccleston** [comment]
Just wondering if you might have a chance to take a look at my proposed changes from July. I think they really improve the script, especially if you have a FrSky sensor that returns a table of values. It would really save some people time who might try to use your script.

Also, thought I'd mention that there were 4 additional commits in August by me on this branch, but they are not part of it (only the one commit from July). I'm new to 'pull requests', and didn't realize they would be grouped into the pull request; and I don't see a way to remove those commits. Perhaps you could cherry pick the one request?

**Review by RCdiy — APPROVED** [review]

**Comment by RCdiy** [comment]
Thank you

**Comment by RCdiy** [comment]
I didn’t do merge so reopened.

**Pull request merged**
